### ISSUE TITLE
for multiclass task safely_select_variable() gives error

### ISSUE THREAD

**Issue by AtharKharal** [MI2DataLab/SAFE#7]
hi, for my multiclass task safely_select_variables() gives following error:
Error in `[.data.frame`(data, , var_best) : undefined columns selected

Following is a dummy code (isomorphic to my original problem), would you please check my last 5 lines. I think I have messed them up. Thanks

library(tidyverse)
library(mlr3verse)
library(DALEX)
library(DALEXtra)
library(rSAFE)

df=data.frame(v=c(3.4,5.6,1.3,9.8,7.3, 4.6,5.5,2.3,8.9,7.1, 4.9,6.5,2.3,4.1,3.37, 3.4,6.0,2.3,7.8,3.7),
              w=c(34,65,23,78,37, 34,65,23,78,37, 34,65,23,78,37, 34,65,23,78,37),
              x=c('a','b','a','c','c', 'a','b','a','c','c', 'a','b','a','c','c', 'a','b','a','c','c'),
              y=c(TRUE,FALSE,TRUE,TRUE,FALSE, TRUE,FALSE,TRUE,TRUE,FALSE, TRUE,FALSE,TRUE,TRUE,FALSE, TRUE,FALSE,TRUE,TRUE,FALSE),
              z=c('alpha','alpha','delta','delta','phi', 'alpha','alpha','delta','delta','phi', 'alpha','alpha','delta','delta','phi', 'alpha','alpha','delta','delta','phi')
)

df_task <- TaskClassif$new(id = "my_df", backend = df, target = "z")
lrn_rf <- GraphLearner$new(po('encode') %>>% lrn("classif.ranger", predict_type = "prob"))
lrn_rf$train(df_task)

lrn_rf_exp <- explain_mlr3(lrn_rf,
                           data = df,
                           y = df$z,
                           label = "rf_exp")
safe_extractor <- safe_extraction(lrn_rf_exp, penalty = 25, verbose = FALSE)
sf_trafo_data <- safely_transform_data(safe_extractor, df, verbose = FALSE)
vars <- safely_select_variables(safe_extractor, sf_trafo_data, which_y = "z", class_pred = 'alpha', verbose = FALSE)

data2 <- safely_transform_data(safe_extractor, df, verbose = FALSE)[,c("z", vars)]

model_lm2 <- lm(z ~ ., data = data2)

**Comment by agosiewska** [comment]
It should work now :)
